name: Delete
on:
  workflow_dispatch:
jobs:
  build:
    name: Delete
    runs-on: ubuntu-latest
    steps:
      - name: remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            unalias rm
            rm -rf personal-website
